spring:
  application:
    name: Cloud-Gateway
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://yahoo.com
          predicates:
            - Path=/test/**
        - id: order
          uri: lb://ORDERAPP
          predicates:
            - Path=/orders/**
ribbon:
  ORDERAPP:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule